### ISSUE TITLE
Set custom error message?

### ISSUE THREAD

**Issue by jaredlt** [brafales/emoji-validator#4]
Hi there, is there a way to set a custom error message?

When I set the validator in my model the form shows the following error to the user:

`Name translation missing: en.activemodel.errors.models.payment_form.attributes.name.has_emojis`

**Comment by brafales** [comment]
Hi @jaredlt, the validator will default to Rails I18n error string. I suggest you have a look at the I18n Rails API in here https://guides.rubyonrails.org/i18n.html, and see how you can override that message in English or any other locale you may be using.

**Comment by jaredlt** [comment]
Gotcha! Thanks for setting me on the right path.

```yml
# config/locales/en.yml
en:
  activemodel:
    errors:
      messages:
        has_emojis: "must not contain emojis"
```
